#!/usr/bin/bash
#  Copyright (C) 2013-06-27 by Niels Neumann - vatriani.nn@googlemail.com
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the
#  Free Software Foundation, Inc.,
#  59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.


case "$1" in
 start)
  /usr/bin/echo -n "enabled" > /sys/class/thermal/thermal_zone0/mode;exit 0;;
 stop)
  /usr/bin/echo -n "disabled" > /sys/class/thermal/thermal_zone0/mode;exit 0;;
 status)
  /usr/bin/cat /sys/class/thermal/thermal_zone0/mode;exit 0;;
 *)
  echo "acerhdf control"
  echo "usage: $0 [MODE]"
  echo ""
  echo "[MODE]"
  echo "start   starts acerhdf modlue"
  echo "stop    stop acerhdf module"
  echo "status  get actual acerhdf module status";exit 0;;
esac
